version: '3.5'

services:

  postgres:
    image: postgres:9.6
    hostname: postgres
    container_name: docker-postgres
    environment:
      - POSTGRES_DB=tasks
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
      - TZ=GMT
    volumes:
      - "./data/postgres:/var/lib/postgresql/data"
    ports:
      - 5433:5432
    restart: always
    logging:
      driver: json-file
      options:
        mode: non-blocking
      
  tasks-api:
    image: com.rsalcir/tasks-api
    build: .
    hostname: tasks-api
    container_name: tasks-api
    depends_on:
      - postgres
    ports:
      - 3000:3000
    command: bash -c "sleep 15 && npm start"
    environment:
      - DATABASE_URL=postgres://postgres:123456@postgres:5432/tasks
    restart: always
    logging:
      driver: json-file
      options:
        mode: non-blocking